/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "cal"
include("cal-core")
include("cal-web")
include("cal-cli")
